### ISSUE TITLE
WiFi on android sucks

### ISSUE THREAD

**Issue by deavmi** [Marlinski/Rumble#31]
Maybe a message should be displayed when using wifi mode about how the infrastructure mode is not the best. With an option to "Not show this message again.". I think this is important as infrastructure mode is crap.

**Comment by Marlinski** [comment]
can you develop as to why infrastructure mode is crap ?

**Comment by deavmi** [comment]
It's all in the word.

Ad-hoc mode allows the network to operate in a more democratic way. If 
it uses infrustructure mode then if the AP goes down then all devices 
connected to it cannot communicate to each other using WiFi as the medium.

**Comment by Marlinski** [comment]
ah well, I couldn't agree more unfortunetly google has been deaf to the issue since 2008:
https://code.google.com/p/android/issues/detail?id=82

Even though wifi chips do provide adhoc support, it is currently not natively supported by android. The only way would be to root the device (as done on the serval project) which is not a requirement I want.

**Comment by deavmi** [comment]
Google should just implement it. They are such bullshitters sometimes, honestly.
